services:
  www:
    build: .
    ports:
      - '80:80'
    volumes:
      - './src:/var/www/html'
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: SchoolManagementSystem
      MYSQL_USER: php_docker
      MYSQL_PASSWORD: password
    volumes:
      - './db:/docker-entrypoint-initdb.d'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db

networks:
  default:
    driver: bridge
